### ISSUE TITLE
feature/Create Payment View

### ISSUE THREAD

**Issue by JingYenLoh** [levi85/diaa-ui#10]
#### [WIP] feature/Create Payment View

Refer to slide 12
##### Sub-Task
- [x] Imp Payment Info Component
- [x] Imp Payment Total Component
- [ ] Imp payment selection Logic (KIV to FE BE integration)
- [ ] Imp Submit (KIV to FE BE integration task)
- [x] Imp Back

**To create separate Card to Implement Backend Integration**
