### ISSUE TITLE
feature/Audit followUp Info view

### ISSUE THREAD

**Issue by levi85** [levi85/diaa-ui#22]
refer to slide 20 - 21  

##### Sub-Task
- [x] Reuse DI Header component
- [x] Reuse DI Line Item List component
- [x] Reuse Audit Findings component
- [x] Impl Settlement Report component

**Comment by JingYenLoh** [comment]
Resolved in #18
