### ISSUE TITLE
eature/Administration

### ISSUE THREAD

**Issue by levi85** [levi85/diaa-ui#25]
refer to slide 22

##### Sub-Task
- [ ] Imp Station
- [ ] Imp CO List
- [ ] Imp SO List
- [ ] Imp AO List
- [ ] Imp Claim Type List
- [ ] Imp Bank Info List
