### ISSUE TITLE
feature/DI List View

### ISSUE THREAD

**Issue by levi85** [levi85/diaa-ui#3]
Refer to slide 2
##### Sub-Task
- [x] Imp Invoices Table Component
- [x] Imp Search Component
- [x] Imp Role Logic
- [x] Imp action buttons

**To create separate Card to Implement Backend Integration**

**Comment by JingYenLoh** [comment]
Resolved by #4
