### ISSUE TITLE
[WIP] feature/DI Info View

### ISSUE THREAD

**Issue by levi85** [levi85/diaa-ui#8]
Refer to slide 3-11
##### Sub-Task
- [ ] Imp DI Header component
- [ ] Imp DI Line Item component
- [ ] Imp Verify Good
- [ ] Imp Reject 
- [ ] Imp Back 
- [ ] Imp PDF Preview Panel
- [ ] Imp Messages Integration
- [ ] Imp Role Logic

**To create separate Card to Implement Backend Integration**

**Comment by JingYenLoh** [comment]
I didn't code messages because I'm not sure how the flow would be for that. We can discuss that tomorrow/today.

For headers and line item presentation, I'd actually prefer to work on them __after__ Friday, and keep them looking simplistic.

**Comment by levi85** [comment]
> I didn't code messages because I'm not sure how the flow would be for that. We can discuss that tomorrow/today.
> 
> For headers and line item presentation, I'd actually prefer to work on them _after_ Friday, and keep them looking simplistic.

My initial message feature was design to be simple which is suppose to notify everyone but there is a feedback from the user on the need to send messages to specific role.

Sure, let's keep each other updated on Monday.
